packages:
  - name: strava
    functions:
      - name: webhook
        runtime: nodejs:18
        web: true
        webSecure: false
        environment:
          STRAVA_VERIFY_TOKEN: "${STRAVA_VERIFY_TOKEN}"
